config/routes.rb
KhanBurmese::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root :to => 'home#index'
  get 'home' => 'home#dashboard', :as => :dashboard
  get 'manage_dash' => 'home#admin_dashboard', :as => :admin_dashboard

  get 'preview' => 'preview#show', :as => :prototype

  get 'download' => 'files#download'

  resources :users, :only => [ :show, :update, :destroy ] do
    collection do
      get 'leaderboard' => 'users#leaderboard'
    end
    put :change_role
  end

  resources :videos do
    put :toggle_star
    resources :translations do
      post 'submit_amara' => 'translations#submit_amara'
      post 'vote' => 'translations#vote'
      post 'review_mail' => 'translations#review_mail'
    end

    collection do
      get :import
      post :import
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  require 'youtube_reader'
  require 'net/http'

  attr_accessible :description, :title, :youtube_id, :starred, :duration
  acts_as_taggable
  acts_as_taggable_on :subject

  has_many :translations, :dependent => :destroy
  has_many :translators, :through => :translations, :source => :user

  validates_presence_of :youtube_id
  validates_uniqueness_of :youtube_id

  before_create :fill_missing_fields

  @@statuses = [ :unassigned, :assigned, :translated, :reviewed ]

  def assigned?
    not self.translations.empty?
  end
  def translated?
    not self.completed_translations.empty?
  end
  def reviewed?
    not self.reviewed_translations.empty?
  end

  def completed_translations
    self.translations.select { |translation| translation.complete? }
  end
  def reviewed_translations
    self.translations.select { |translation| translation.reviewed? }
  end

  def reviewers
    self.completed_translations.map { |translation| translation.reviewers }.flatten
  end

  def youtube_link
    "http://www.youtube.com/embed/#{self.youtube_id}"
  end

  def amara_link
    "http://www.amara.org/en/subtitles/editor/#{self.amara_id}/my/"
  end

  def amara_en_srt
    link = "http://www.amara.org/en/videos/#{self.amara_id}/en/"

    Video.get_srt_link_from_amara(link)
  end

  def status
    if self.assigned?
      return :reviewed if self.reviewed?
      return :translated if self.translated?
      :assigned
    else
      :unassigned
    end
  end

  def update_from_hash(video_hash)
    keys = [ 'description', 'title' ]
    self.update_attributes(video_hash.slice(*keys))

    self.subject_list = video_hash['subject']

    if self.save and video_hash['translated?'] and video_hash['translated?'].downcase != 'false'
      translation = Translation.new(:video => self)

      begin
        link = "http://www.amara.org/en/videos/#{self.amara_id}/my/"
        translation.upload_amara(link)
      rescue ArgumentError => e
        self.errors.add(:base, e.message)
      end
    end

    self
  end

  def fill_missing_fields
    youtube_values = {}

    begin
      youtube_values = YoutubeReader::parse_video(self.youtube_id)
    rescue ArgumentError => e
      self.errors.add(:base, "#{e.message} for \"#{self.title}\" video.")
      return false
    end

    unless youtube_values.empty?
      fields = [ 'description', 'title', 'duration' ]
      fields.each do |field|
        write_attribute(field, youtube_values[field]) if self[field].blank?
      end
    end

    write_attribute(:amara_id, YoutubeReader::amara_id(self.youtube_id))
  end

  def similar
    Video.search(nil, ['unassigned', 'assigned'], self.subject_list) - [self]
  end

  def self.recently_translated_videos(time)
    Video.all.select do |video|
      recent = false
      video.translations.each do |translation|
        recent = true if translation.complete? and translation.time_updated > time
      end

      recent
    end
  end

  def self.priority_videos
    Video.where(:starred => true)
  end

  def self.statuses
    @@statuses
  end

  def self.all_subjects
    Video.subject_counts.map { |subject| subject.name }
  end

  def self.search(search, statuses = [], subjects = [])
    videos = scoped

    if search
      videos = videos.where('lower(title) LIKE ?', "%#{search.downcase}%")
    end

    if subjects and not subjects.empty?
      videos = videos.select { |video| not (video.subject_list & subjects).empty? }
    end

    if statuses and not statuses.empty?
      videos = videos.select { |video| statuses.include?(video.status.to_s) }
    end

    videos
  end

  def self.verify_csv(file)
    unless file
      raise ArgumentError, 'Missing file.'
    end

    if File.extname(file.original_filename) != ".csv"
      raise ArgumentError, 'Invalid file type.'
    end
  end

  def self.get_srt_link_from_amara(amara_link)
    result = Net::HTTP.get_response(URI.parse(amara_link))
    return nil if [ '404', '403' ].include?(result.code)
    result = Net::HTTP.get_response(URI.parse(result.header['location'])) if [ '302', '301' ].include?(result.code)

    srt_link_match = /<a href="([^"]*)">SRT<\/a>/.match(result.body)
    return nil if srt_link_match.nil?
    "http://www.amara.org/#{srt_link_match[1]}"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.search(params[:search], params[:statuses], params[:subjects]).sort_by {
      |video| video.starred ? 0 : 1
    }
    @subjects = Video.all_subjects

    @statuses = Video.statuses.map(&:to_s)

    @default_params = {}
    params[:statuses].each { |status| @default_params[status] = true } if params[:statuses]
  end

  def show
    @video = Video.find(params[:id])
    @user_translation = Translation.find_by_video_id_and_user_id(@video, current_user)
    @completed_translations = @video.completed_translations
    @translators = @video.translators.take(4)
    @reviewers = (@video.reviewers - @video.translators).take(4)
    @similar_videos = @video.similar.take(5)
  end

  def toggle_star
    @video = Video.find(params[:video_id])
    authorize! :star, @video

    @video.toggle :starred
    @video.save
  end

  def import
    authorize! :import, :video

    unless request.post?
      @last_import = Import.order(:time_imported).last
      return
    end

    begin
      Video.verify_csv(params[:file])
    rescue ArgumentError => e
      add_flash(:alert, e.message)
      redirect_to import_videos_path
      return
    end

    import = Import.create
    CSV.foreach(params[:file].path, :headers => true) do |row|
      ImportVideoWorker.perform_async(import.id, row.to_hash)
    end

    add_flash(:notice, 'Your videos are importing, which may take a while. Check back at this page for updates.')
    redirect_to import_videos_path
  end

  def new
    authorize! :import, :video

    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
    authorize! :update, @video
  end

  def create
    authorize! :import, :video

    video = Video.new(:youtube_id => params[:video][:youtube_id]).update_from_hash(params[:video])
    if video.save
      redirect_to video_path(video)
    else
      video.errors.full_messages.each { |error| add_flash(:alert, error) }
      redirect_to new_video_path
    end
  end

  def update
    @video = Video.find(params[:id])
    authorize! :update, @video

    @video.update_from_hash(params[:video])
    if @video.save
      redirect_to video_path(@video)
    else
      @video.errors.full_messages.each { |error| add_flash(:alert, error) }
      redirect_to new_video_path
    end
  end

  def destroy
    @video = Video.find(params[:id])
    authorize! :destroy, @video

    @video.destroy
    redirect_to videos_path
  end
end

app/helpers/video_helper.rb
module VideoHelper
  def toggle_star_button(video)
    i_starred = '<i class="fa fa-lg fa-star fa-star-starred fa-fw"></i>'.html_safe
    i_unstarred = '<i class="fa fa-lg fa-star fa-star-unstarred fa-fw"></i>'.html_safe

    html = ''
    if can? :star, video
      i_class = ''
      options = { :'data-method' => :put, :remote => true, :onclick => 'starClick(this);' }

      if video.starred
        i_class = i_starred
      else
        i_class = i_unstarred
      end

      html += link_to video_toggle_star_path(video), options do
        i_class
      end
    else
      if video.starred
        html += i_starred
      end
    end

    html.html_safe
  end

  def toggle_vote_button(vote, video, translation, options = {})
    voted = current_user.voted_as_when_voted_on(translation) == vote

    vote_class = vote ? 'upvote' : 'downvote'

    icon_class = vote ? 'fa-sort-asc' : 'fa-sort-desc'
    icon_class += ' active' if voted

    content_tag :span, :class => 'vote' do
      link_to('', video_translation_vote_path(video, translation, :vote => vote), {
        :'data-method' => :post,
        :remote => true,
        :class => "#{vote_class}-link"
      }.merge(options)) + "<i class=\"fa fa-lg #{icon_class} #{vote_class}\"></i>".html_safe
    end
  end

  def score_badge(score)
    badge_class = 'badge vote-badge'
    badge_class += ' danger' if score < 0

    content_tag :span, score, :class => badge_class
  end

  def status_to_color(status)
    case status.to_s
    when 'unassigned' then 'danger'
    when 'assigned' then 'warning'
    when 'translated' then 'primary'
    when 'reviewed' then 'success'
    end
  end
end

app/views/videos/show/_actions.html.erb
<div class="btn-module">
  <% review_class = 'btn-block' %>
  <% if translation.nil? %>
    <%= link_to 'Assign to Me', video_translations_path(video), :class => 'btn btn-primary btn-left', :'data-method' => :post %>
    <% review_class = 'btn-right' %>
  <% elsif not translation.complete? %>
    <%= link_to 'Unassign Me', '#', :class => 'btn btn-danger btn-left', :data => { :toggle => 'modal', :target => '#deleteModal' } %>
    <% review_class = 'btn-right' %>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content module">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="deleteModalLabel">Confirm Unassignment</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to cancel this assignment? This will put this video back on the market for other users to translate.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
            <%= link_to 'Unassign', video_translation_path(video, translation), :class => 'btn btn-danger', :'data-method' => :delete %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to 'Review', '#review', :id => 'review-link', :class => "btn btn-success #{review_class}" %>
</div>

app/views/videos/show/_contributor_row.html.erb
<div class="media">
  <div class="media-left media-middle">
    <a href="#">
      <%= link_to user_path(contributor) do %>
        <%= image_tag 'avatar.jpg', :class => 'img-circle media-object profile-pic' %>
      <% end %>
    </a>
  </div>
  <div class="media-body">
    <p class="media-heading"><%= contributor.name %></p>
    <span class="badge badge-<%= role %>"><%= role.titleize %></span>
  </div>
</div>

app/views/videos/show/_contributors_frame.html.erb
<div class="panel panel-default module">
  <div class="panel-heading">
    <b>Contributors</b>
    <a class="pull-right" href="#"><i class="fa fa-plus-circle"></i></a>
  </div>
  <% if translators.empty? and reviewers.empty? %>
    <div class="panel-empty">
      No one has contributed yet!
    </div>
  <% else %>
    <%= render :partial => 'videos/show/contributor_row',
      :collection => translators,
      :as => :contributor,
      :locals => { :role => 'translator' }
    %>
    <%= render :partial => 'videos/show/contributor_row',
      :collection => reviewers,
      :as => :contributor,
      :locals => { :role => 'reviewer' }
    %>
  <% end %>
</div>

app/views/videos/show/_similar_videos_frame.html.erb
<div class="panel panel-default module module-videos">
  <div class="panel-heading">
    <b>Similar Videos</b>
  </div>
  <div class="panel-content">
    <% if videos.empty? %>
      <div class="panel-empty">
        Couldn't find any similar videos!
      </div>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Duration</th>
          </tr>
        </thead>
        <tbody>
          <%= render :partial => 'videos/show/similar_videos_row',
            :collection => videos,
            :as => :video
          %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/videos/show/_similar_videos_row.html.erb
<tr>
  <td><%= link_to video.title, video, :class => 'row-title' %></td>
  <td><%= seconds_to_string(video.duration) %></td>
</tr>

app/views/videos/show/_translate_frame.html.erb
<% if translation %>
  <div id="translate">
    <div class="panel-tabs">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active tab-translation">
          <a href="#tab-amara" class="panel-title-tabs" aria-controls="home" role="tab" data-toggle="tab">
            Translate on Amara
          </a>
        </li>
        <li role="presentation" class="tab-translation">
          <a href="#tab-srt" class="panel-title-tabs" aria-controls="srt" role="tab" data-toggle="tab">
            Translate Offline
          </a>
        </li>
      </ul>
    </div>

    <div class="panel panel-default module module-padding module-tabs">
      <div role="tabpanel">
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane fade in active tab-amara" id="tab-amara">
            <span>If you'd like to use Amara's translation interface, you can use the <b><%= link_to 'link to the Amara video', video.amara_link, :target => '_amara' %></b>. To earn points, submit your published Amara link below. You can find this link by clicking <b>Burmese</b> in the languages panel.</span>

            <%= form_tag(video_translation_submit_amara_path(video, translation), :class => 'tab-form', :multipart => true) do %>
              <div class="input-group">
                <%= text_field_tag :amara_link, nil, :class => 'form-control', :placeholder => 'Copy your Amara link here.' %>
                <div class="input-group-btn">
                  <%= submit_tag 'Submit', :class => 'btn btn-primary' %>
                </div>
              </div>
            <% end %>
          </div>
          <div role="tabpanel" class="tab-pane fade tab-srt" id="tab-srt">
            <span>
            <% if (srt_link = video.amara_en_srt) %>
              If you want to translate offline using an SRT, you can <b><%= link_to 'download the video\'s SRT', srt_link %></b>.
            <% else %>
              Unfortunately, there is no English SRT available. You can use audio from the video above to translate.
            <% end %>
            When you're finished translating, use the following steps to get credit for your work:</span>

            <ol class="upload-steps">
              <li>Visit the <b><%= link_to 'Amara link', video.amara_link, :target => '_amara' %></b>.</li>
              <li>Hover over the wrench and click <b>Upload Subtitles</b>.</li>
              <li>Follow the steps to finish subtitling the video, and click <b>Publish</b> to complete.</li>
              <li>In the languages panel, click <b>Burmese</b>. Copy the URL of the page.</li>
              <li>Navigate to the tab on the left, <b>Translate on Amara</b>, on this page. Paste your link and hit <b>Submit</b>.</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/videos/show/_video_frame.html.erb
<div class="panel panel-default module">
  <div class="panel-heading">
    <b><%= video.title %></b>
    <% if can? :update, video %>
      <%= link_to edit_video_path(video), :class => 'link-edit-video' do %>
        <i class="fa fa-pencil"></i></i>
      <% end %>
    <% end %>
    <div id="toggle-star-<%= @video.id %>" class="pull-right">
      <%= toggle_star_button(video) %>
    </div>
  </div>

  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="<%= video.youtube_link %>" frameborder="0" allowfullscreen></iframe>
  </div>

  <div class="video-footer">
    <div class="pull-left"><b>Subject: <%= video.subject_list.join(', ') %></b></div>
    <div class="pull-right"><b>Duration: <%= seconds_to_string(video.duration) %></b></div>
  </div>
</div>