config/routes.rb
KhanBurmese::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root :to => 'home#index'
  get 'home' => 'home#dashboard', :as => :dashboard
  get 'manage_dash' => 'home#admin_dashboard', :as => :admin_dashboard

  get 'preview' => 'preview#show', :as => :prototype

  get 'download' => 'files#download'

  resources :users, :only => [ :show, :update, :destroy ] do
    collection do
      get 'leaderboard' => 'users#leaderboard'
    end
    put :change_role
  end

  resources :videos do
    put :toggle_star
    resources :translations do
      post 'submit_amara' => 'translations#submit_amara'
      post 'vote' => 'translations#vote'
      post 'review_mail' => 'translations#review_mail'
    end

    collection do
      get :import
      post :import
    end
  end

end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
  attr_accessible :user, :video, :srt
  acts_as_votable

  has_attached_file :srt,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :dropbox_visibility => 'private',
    :path => "#{Rails.env}/srt/:id/translation.srt"

  validates_presence_of :video
  validates_uniqueness_of :user_id, :scope => :video_id

  after_create :update_time

  # Maps from integer representation in the database to status symbol:
  @@STATUS_HASH = { 0 => :incomplete, 1 => :complete, 2 => :complete_with_priority }

  # Maps from status symbol to point value:
  @@POINTS_HASH = { :incomplete => 0, :complete => 1, :complete_with_priority => 2 }

  # Maps from status symbol to integer representation for database:
  @@STATUS_TO_INT_HASH = @@STATUS_HASH.invert

  def user
    super || User.anonymous_user
  end

  def points
    @@POINTS_HASH[self.status_symbol]
  end

  def reviewers
    self.votes_for.voters
  end

  def net_votes
    self.get_upvotes.size - self.get_downvotes.size
  end

  def status_symbol
    return @@STATUS_HASH[self.status]
  end

  def time_assigned
    self.created_at
  end

  def time_updated
    self.time_last_updated
  end

  def reviewed?
    self.net_votes > 0
  end

  def anonymous_translator?
    user_id.nil?
  end

  def complete
    unless self.complete?
      new_status = self.video.starred ? @@STATUS_TO_INT_HASH[:complete_with_priority] : @@STATUS_TO_INT_HASH[:complete]
      self.status = new_status
      self.save
    end
  end

  def complete?
    [ :complete_with_priority, :complete ].include? self.status_symbol
  end

  def upload_amara(amara_link)
    amara_link = amara_link.gsub('https', 'http')
    Translation.verify_link(amara_link)

    srt_link = Video.get_srt_link_from_amara(amara_link)
    raise ArgumentError, "No SRT published for #{video.title}." unless srt_link

    self.srt = URI.parse(srt_link)
    self.save

    update_time
    complete
  end

  private
  def update_time
    self.time_last_updated = Time.now
    self.save
  end

  def self.verify_file(srt)
    if srt.nil?
      raise ArgumentError, 'Missing file.'
    elsif File.extname(srt.original_filename) != '.srt' 
      raise ArgumentError, 'Invalid file type.'
    end
  end

  def self.verify_link(amara_link)
    unless amara_link =~ /^http:\/\/www.amara.org\/en\/videos\/([\w\d]+)\/my(\/(\d+))?\/?$/
      raise ArgumentError, 'Invalid link format.'
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  require 'youtube_reader'
  require 'net/http'

  attr_accessible :description, :title, :youtube_id, :starred, :duration
  acts_as_taggable
  acts_as_taggable_on :subject

  has_many :translations, :dependent => :destroy
  has_many :translators, :through => :translations, :source => :user

  validates_presence_of :youtube_id
  validates_uniqueness_of :youtube_id

  before_create :fill_missing_fields

  @@statuses = [ :unassigned, :assigned, :translated, :reviewed ]

  def assigned?
    not self.translations.empty?
  end
  def translated?
    not self.completed_translations.empty?
  end
  def reviewed?
    not self.reviewed_translations.empty?
  end

  def completed_translations
    self.translations.select { |translation| translation.complete? }
  end
  def reviewed_translations
    self.translations.select { |translation| translation.reviewed? }
  end

  def reviewers
    self.completed_translations.map { |translation| translation.reviewers }.flatten
  end

  def youtube_link
    "http://www.youtube.com/embed/#{self.youtube_id}"
  end

  def amara_link
    "http://www.amara.org/en/subtitles/editor/#{self.amara_id}/my/"
  end

  def amara_en_srt
    link = "http://www.amara.org/en/videos/#{self.amara_id}/en/"

    Video.get_srt_link_from_amara(link)
  end

  def status
    if self.assigned?
      return :reviewed if self.reviewed?
      return :translated if self.translated?
      :assigned
    else
      :unassigned
    end
  end

  def update_from_hash(video_hash)
    keys = [ 'description', 'title' ]
    self.update_attributes(video_hash.slice(*keys))

    self.subject_list = video_hash['subject']

    if self.save and video_hash['translated?'] and video_hash['translated?'].downcase != 'false'
      translation = Translation.new(:video => self)

      begin
        link = "http://www.amara.org/en/videos/#{self.amara_id}/my/"
        translation.upload_amara(link)
      rescue ArgumentError => e
        self.errors.add(:base, e.message)
      end
    end

    self
  end

  def fill_missing_fields
    youtube_values = {}

    begin
      youtube_values = YoutubeReader::parse_video(self.youtube_id)
    rescue ArgumentError => e
      self.errors.add(:base, "#{e.message} for \"#{self.title}\" video.")
      return false
    end

    unless youtube_values.empty?
      fields = [ 'description', 'title', 'duration' ]
      fields.each do |field|
        write_attribute(field, youtube_values[field]) if self[field].blank?
      end
    end

    write_attribute(:amara_id, YoutubeReader::amara_id(self.youtube_id))
  end

  def similar
    Video.search(nil, ['unassigned', 'assigned'], self.subject_list) - [self]
  end

  def self.recently_translated_videos(time)
    Video.all.select do |video|
      recent = false
      video.translations.each do |translation|
        recent = true if translation.complete? and translation.time_updated > time
      end

      recent
    end
  end

  def self.priority_videos
    Video.where(:starred => true)
  end

  def self.statuses
    @@statuses
  end

  def self.all_subjects
    Video.subject_counts.map { |subject| subject.name }
  end

  def self.search(search, statuses = [], subjects = [])
    videos = scoped

    if search
      videos = videos.where('lower(title) LIKE ?', "%#{search.downcase}%")
    end

    if subjects and not subjects.empty?
      videos = videos.select { |video| not (video.subject_list & subjects).empty? }
    end

    if statuses and not statuses.empty?
      videos = videos.select { |video| statuses.include?(video.status.to_s) }
    end

    videos
  end

  def self.verify_csv(file)
    unless file
      raise ArgumentError, 'Missing file.'
    end

    if File.extname(file.original_filename) != ".csv"
      raise ArgumentError, 'Invalid file type.'
    end
  end

  def self.get_srt_link_from_amara(amara_link)
    result = Net::HTTP.get_response(URI.parse(amara_link))
    return nil if [ '404', '403' ].include?(result.code)
    result = Net::HTTP.get_response(URI.parse(result.header['location'])) if [ '302', '301' ].include?(result.code)

    srt_link_match = /<a href="([^"]*)">SRT<\/a>/.match(result.body)
    return nil if srt_link_match.nil?
    "http://www.amara.org/#{srt_link_match[1]}"
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def create
    @video = Video.find(params[:video_id])
    @translation = Translation.new(:video => @video, :user => current_user)

    unless @translation.save
      @translation.errors.full_messages.each do |error|
        add_flash(:alert, error)
      end
    end

    redirect_to video_path @video
  end

  def destroy
    @video = Video.find(params[:video_id])
    @translation = Translation.find(params[:id])

    authorize! :destroy, @translation

    @translation.destroy
    redirect_to video_path @video
  end

  def submit_amara
    @video = Video.find(params[:video_id])
    @translation = Translation.find(params[:translation_id])

    authorize! :upload, @translation

    begin
      @translation.upload_amara(params[:amara_link])
    rescue ArgumentError => e
      add_flash(:alert, e.message)
    end
    redirect_to video_path @video
  end

  def vote
    @video = Video.find(params[:video_id])
    @translation = Translation.find(params[:translation_id])

    authorize! :review, @translation

    if current_user.voted_as_when_voted_on(@translation).to_s == params[:vote]
      current_user.unvote_for @translation
    else
      @translation.vote_by :voter => current_user, :vote => params[:vote]
    end

    render 'videos/vote'
  end

  def review_mail
    @translation = Translation.find(params[:translation_id])
    @message = h(params[:message]).gsub(/\n/, '<br />').html_safe

    authorize! :review, @translation

    UserMailer.translation_review_email(@translation, current_user, @message).deliver

    add_flash(:notice, 'Your message has been sent!')
    redirect_to :back
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.search(params[:search], params[:statuses], params[:subjects]).sort_by {
      |video| video.starred ? 0 : 1
    }
    @subjects = Video.all_subjects

    @statuses = Video.statuses.map(&:to_s)

    @default_params = {}
    params[:statuses].each { |status| @default_params[status] = true } if params[:statuses]
  end

  def show
    @video = Video.find(params[:id])
    @user_translation = Translation.find_by_video_id_and_user_id(@video, current_user)
    @completed_translations = @video.completed_translations
    @translators = @video.translators.take(4)
    @reviewers = (@video.reviewers - @video.translators).take(4)
    @similar_videos = @video.similar.take(5)
  end

  def toggle_star
    @video = Video.find(params[:video_id])
    authorize! :star, @video

    @video.toggle :starred
    @video.save
  end

  def import
    authorize! :import, :video

    unless request.post?
      @last_import = Import.order(:time_imported).last
      return
    end

    begin
      Video.verify_csv(params[:file])
    rescue ArgumentError => e
      add_flash(:alert, e.message)
      redirect_to import_videos_path
      return
    end

    import = Import.create
    CSV.foreach(params[:file].path, :headers => true) do |row|
      ImportVideoWorker.perform_async(import.id, row.to_hash)
    end

    add_flash(:notice, 'Your videos are importing, which may take a while. Check back at this page for updates.')
    redirect_to import_videos_path
  end

  def new
    authorize! :import, :video

    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
    authorize! :update, @video
  end

  def create
    authorize! :import, :video

    video = Video.new(:youtube_id => params[:video][:youtube_id]).update_from_hash(params[:video])
    if video.save
      redirect_to video_path(video)
    else
      video.errors.full_messages.each { |error| add_flash(:alert, error) }
      redirect_to new_video_path
    end
  end

  def update
    @video = Video.find(params[:id])
    authorize! :update, @video

    @video.update_from_hash(params[:video])
    if @video.save
      redirect_to video_path(@video)
    else
      @video.errors.full_messages.each { |error| add_flash(:alert, error) }
      redirect_to new_video_path
    end
  end

  def destroy
    @video = Video.find(params[:id])
    authorize! :destroy, @video

    @video.destroy
    redirect_to videos_path
  end
end

app/helpers/video_helper.rb
module VideoHelper
  def toggle_star_button(video)
    i_starred = '<i class="fa fa-lg fa-star fa-star-starred fa-fw"></i>'.html_safe
    i_unstarred = '<i class="fa fa-lg fa-star fa-star-unstarred fa-fw"></i>'.html_safe

    html = ''
    if can? :star, video
      i_class = ''
      options = { :'data-method' => :put, :remote => true, :onclick => 'starClick(this);' }

      if video.starred
        i_class = i_starred
      else
        i_class = i_unstarred
      end

      html += link_to video_toggle_star_path(video), options do
        i_class
      end
    else
      if video.starred
        html += i_starred
      end
    end

    html.html_safe
  end

  def toggle_vote_button(vote, video, translation, options = {})
    voted = current_user.voted_as_when_voted_on(translation) == vote

    vote_class = vote ? 'upvote' : 'downvote'

    icon_class = vote ? 'fa-sort-asc' : 'fa-sort-desc'
    icon_class += ' active' if voted

    content_tag :span, :class => 'vote' do
      link_to('', video_translation_vote_path(video, translation, :vote => vote), {
        :'data-method' => :post,
        :remote => true,
        :class => "#{vote_class}-link"
      }.merge(options)) + "<i class=\"fa fa-lg #{icon_class} #{vote_class}\"></i>".html_safe
    end
  end

  def score_badge(score)
    badge_class = 'badge vote-badge'
    badge_class += ' danger' if score < 0

    content_tag :span, score, :class => badge_class
  end

  def status_to_color(status)
    case status.to_s
    when 'unassigned' then 'danger'
    when 'assigned' then 'warning'
    when 'translated' then 'primary'
    when 'reviewed' then 'success'
    end
  end
end

app/views/videos/translations/_downvote_modal.html.erb
<% unless translation.anonymous_translator? %>
  <div class="modal fade" id="downvoteModal<%= translation.id %>" tabindex="-1" role="dialog" aria-labelledby="downvoteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content module">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="deleteModalLabel">Constructive Criticism</h4>
        </div>
        <%= form_tag video_translation_review_mail_path(video, translation) do %>
          <div class="modal-body">
            <p>You've just downvoted <%= translation.user.first_name %>'s translation. Care to give them some advice on how to make it better?</p>
            <%= text_area_tag 'message', nil, {
              :placeholder => 'Write your criticisms here.',
              :class => 'form-control'
            } %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
            <%= submit_tag 'Send', :class => 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/videos/translations/_translation_row.html.erb
<tr>
  <td>
    <div id="vote-translation-<%= translation.id %>" class="vote-group" title="Review This Translation" data-toggle="tooltip" data-placement="left">
      <%= render 'videos/translations/vote_actions', :video => video, :translation => translation %>
    </div>
  </td>
  <td>
    <% user_url = translation.anonymous_translator? ? nil : translation.user %>
    <%= link_to_unless translation.anonymous_translator?, translation.user.name, user_url, :class => 'row-title' %>
  </td>
  <td><%= translation.time_updated.localtime.strftime("%B %d, %Y at %l:%M") %></td>
  <td>
    <%= link_to 'Download', translation.srt.url(:download => true), :class => 'btn btn-success btn-xs' %>
  </td>
</tr>

app/views/videos/translations/_translations_frame.html.erb
<% tooltip_title = translations.empty? ? 'Sorry, nothing to review.' : 'Review translations here!' %>
<div id="review" title="<%= tooltip_title %>" class="panel panel-default module module-videos" data-trigger="manual">
  <div class="panel-heading">
    <b>Recent Translations</b>
  </div>
  <div class="panel-content">
    <% if translations.empty? %>
      <div class="panel-empty">
        No translations yet. Be the first to make one!
      </div>
    <% else %>
      <%= render 'videos/translations/translations_table', :video => video, :translations => translations %>
      <%= render :partial => 'videos/translations/downvote_modal',
        :collection => translations,
        :as => :translation,
        :locals => { :video => video }
      %>
    <% end %>
  </div>
</div>

app/views/videos/translations/_translations_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Author</th>
      <th>Updated</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'videos/translations/translation_row',
      :collection => translations,
      :as => :translation,
      :locals => { :video => video }
    %>
  </tbody>
</table>

app/views/videos/translations/_vote_actions.html.erb
<% if can? :review, translation %>
  <%= toggle_vote_button(true, video, translation) %>
  <% data = {} %>
  <% data = {
    :toggle => 'modal',
    :target => "#downvoteModal#{translation.id}"
  } if current_user.voted_as_when_voted_on(translation) != false %>
  <%= toggle_vote_button(false, video, translation, {
    :data => data
  }) %>
<% end %>

<%= score_badge(translation.net_votes) %>