config/routes.rb
KhanBurmese::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root :to => 'home#index'
  get 'home' => 'home#dashboard', :as => :dashboard
  get 'manage_dash' => 'home#admin_dashboard', :as => :admin_dashboard

  get 'preview' => 'preview#show', :as => :prototype

  get 'download' => 'files#download'

  resources :users, :only => [ :show, :update, :destroy ] do
    collection do
      get 'leaderboard' => 'users#leaderboard'
    end
    put :change_role
  end

  resources :videos do
    put :toggle_star
    resources :translations do
      post 'submit_amara' => 'translations#submit_amara'
      post 'vote' => 'translations#vote'
      post 'review_mail' => 'translations#review_mail'
    end

    collection do
      get :import
      post :import
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  require 'youtube_reader'
  require 'net/http'

  attr_accessible :description, :title, :youtube_id, :starred, :duration
  acts_as_taggable
  acts_as_taggable_on :subject

  has_many :translations, :dependent => :destroy
  has_many :translators, :through => :translations, :source => :user

  validates_presence_of :youtube_id
  validates_uniqueness_of :youtube_id

  before_create :fill_missing_fields

  @@statuses = [ :unassigned, :assigned, :translated, :reviewed ]

  def assigned?
    not self.translations.empty?
  end
  def translated?
    not self.completed_translations.empty?
  end
  def reviewed?
    not self.reviewed_translations.empty?
  end

  def completed_translations
    self.translations.select { |translation| translation.complete? }
  end
  def reviewed_translations
    self.translations.select { |translation| translation.reviewed? }
  end

  def reviewers
    self.completed_translations.map { |translation| translation.reviewers }.flatten
  end

  def youtube_link
    "http://www.youtube.com/embed/#{self.youtube_id}"
  end

  def amara_link
    "http://www.amara.org/en/subtitles/editor/#{self.amara_id}/my/"
  end

  def amara_en_srt
    link = "http://www.amara.org/en/videos/#{self.amara_id}/en/"

    Video.get_srt_link_from_amara(link)
  end

  def status
    if self.assigned?
      return :reviewed if self.reviewed?
      return :translated if self.translated?
      :assigned
    else
      :unassigned
    end
  end

  def update_from_hash(video_hash)
    keys = [ 'description', 'title' ]
    self.update_attributes(video_hash.slice(*keys))

    self.subject_list = video_hash['subject']

    if self.save and video_hash['translated?'] and video_hash['translated?'].downcase != 'false'
      translation = Translation.new(:video => self)

      begin
        link = "http://www.amara.org/en/videos/#{self.amara_id}/my/"
        translation.upload_amara(link)
      rescue ArgumentError => e
        self.errors.add(:base, e.message)
      end
    end

    self
  end

  def fill_missing_fields
    youtube_values = {}

    begin
      youtube_values = YoutubeReader::parse_video(self.youtube_id)
    rescue ArgumentError => e
      self.errors.add(:base, "#{e.message} for \"#{self.title}\" video.")
      return false
    end

    unless youtube_values.empty?
      fields = [ 'description', 'title', 'duration' ]
      fields.each do |field|
        write_attribute(field, youtube_values[field]) if self[field].blank?
      end
    end

    write_attribute(:amara_id, YoutubeReader::amara_id(self.youtube_id))
  end

  def similar
    Video.search(nil, ['unassigned', 'assigned'], self.subject_list) - [self]
  end

  def self.recently_translated_videos(time)
    Video.all.select do |video|
      recent = false
      video.translations.each do |translation|
        recent = true if translation.complete? and translation.time_updated > time
      end

      recent
    end
  end

  def self.priority_videos
    Video.where(:starred => true)
  end

  def self.statuses
    @@statuses
  end

  def self.all_subjects
    Video.subject_counts.map { |subject| subject.name }
  end

  def self.search(search, statuses = [], subjects = [])
    videos = scoped

    if search
      videos = videos.where('lower(title) LIKE ?', "%#{search.downcase}%")
    end

    if subjects and not subjects.empty?
      videos = videos.select { |video| not (video.subject_list & subjects).empty? }
    end

    if statuses and not statuses.empty?
      videos = videos.select { |video| statuses.include?(video.status.to_s) }
    end

    videos
  end

  def self.verify_csv(file)
    unless file
      raise ArgumentError, 'Missing file.'
    end

    if File.extname(file.original_filename) != ".csv"
      raise ArgumentError, 'Invalid file type.'
    end
  end

  def self.get_srt_link_from_amara(amara_link)
    result = Net::HTTP.get_response(URI.parse(amara_link))
    return nil if [ '404', '403' ].include?(result.code)
    result = Net::HTTP.get_response(URI.parse(result.header['location'])) if [ '302', '301' ].include?(result.code)

    srt_link_match = /<a href="([^"]*)">SRT<\/a>/.match(result.body)
    return nil if srt_link_match.nil?
    "http://www.amara.org/#{srt_link_match[1]}"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.search(params[:search], params[:statuses], params[:subjects]).sort_by {
      |video| video.starred ? 0 : 1
    }
    @subjects = Video.all_subjects

    @statuses = Video.statuses.map(&:to_s)

    @default_params = {}
    params[:statuses].each { |status| @default_params[status] = true } if params[:statuses]
  end

  def show
    @video = Video.find(params[:id])
    @user_translation = Translation.find_by_video_id_and_user_id(@video, current_user)
    @completed_translations = @video.completed_translations
    @translators = @video.translators.take(4)
    @reviewers = (@video.reviewers - @video.translators).take(4)
    @similar_videos = @video.similar.take(5)
  end

  def toggle_star
    @video = Video.find(params[:video_id])
    authorize! :star, @video

    @video.toggle :starred
    @video.save
  end

  def import
    authorize! :import, :video

    unless request.post?
      @last_import = Import.order(:time_imported).last
      return
    end

    begin
      Video.verify_csv(params[:file])
    rescue ArgumentError => e
      add_flash(:alert, e.message)
      redirect_to import_videos_path
      return
    end

    import = Import.create
    CSV.foreach(params[:file].path, :headers => true) do |row|
      ImportVideoWorker.perform_async(import.id, row.to_hash)
    end

    add_flash(:notice, 'Your videos are importing, which may take a while. Check back at this page for updates.')
    redirect_to import_videos_path
  end

  def new
    authorize! :import, :video

    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
    authorize! :update, @video
  end

  def create
    authorize! :import, :video

    video = Video.new(:youtube_id => params[:video][:youtube_id]).update_from_hash(params[:video])
    if video.save
      redirect_to video_path(video)
    else
      video.errors.full_messages.each { |error| add_flash(:alert, error) }
      redirect_to new_video_path
    end
  end

  def update
    @video = Video.find(params[:id])
    authorize! :update, @video

    @video.update_from_hash(params[:video])
    if @video.save
      redirect_to video_path(@video)
    else
      @video.errors.full_messages.each { |error| add_flash(:alert, error) }
      redirect_to new_video_path
    end
  end

  def destroy
    @video = Video.find(params[:id])
    authorize! :destroy, @video

    @video.destroy
    redirect_to videos_path
  end
end

app/helpers/video_helper.rb
module VideoHelper
  def toggle_star_button(video)
    i_starred = '<i class="fa fa-lg fa-star fa-star-starred fa-fw"></i>'.html_safe
    i_unstarred = '<i class="fa fa-lg fa-star fa-star-unstarred fa-fw"></i>'.html_safe

    html = ''
    if can? :star, video
      i_class = ''
      options = { :'data-method' => :put, :remote => true, :onclick => 'starClick(this);' }

      if video.starred
        i_class = i_starred
      else
        i_class = i_unstarred
      end

      html += link_to video_toggle_star_path(video), options do
        i_class
      end
    else
      if video.starred
        html += i_starred
      end
    end

    html.html_safe
  end

  def toggle_vote_button(vote, video, translation, options = {})
    voted = current_user.voted_as_when_voted_on(translation) == vote

    vote_class = vote ? 'upvote' : 'downvote'

    icon_class = vote ? 'fa-sort-asc' : 'fa-sort-desc'
    icon_class += ' active' if voted

    content_tag :span, :class => 'vote' do
      link_to('', video_translation_vote_path(video, translation, :vote => vote), {
        :'data-method' => :post,
        :remote => true,
        :class => "#{vote_class}-link"
      }.merge(options)) + "<i class=\"fa fa-lg #{icon_class} #{vote_class}\"></i>".html_safe
    end
  end

  def score_badge(score)
    badge_class = 'badge vote-badge'
    badge_class += ' danger' if score < 0

    content_tag :span, score, :class => badge_class
  end

  def status_to_color(status)
    case status.to_s
    when 'unassigned' then 'danger'
    when 'assigned' then 'warning'
    when 'translated' then 'primary'
    when 'reviewed' then 'success'
    end
  end
end

app/views/videos/_video_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <b>Videos Listing</b>
  </div>
  <table class="table">
    <tbody>
      <% @videos.each do |video| %>
        <%= render 'video_row', video: video %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/videos/edit.html.erb
<div class="row centered-form">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default module">
      <div class="panel-heading">
        Edit Video "<%= @video.title %>"
      </div>
      <div class="panel-body">
        <%= form_for @video, :url => video_path(@video), :method => :put, :html => { :class => 'form-update' } do |f| %>
          <div class="form-group">
            <%= f.text_field :title, :autofocus => true, :class => 'form-control', :placeholder => 'Title' %>
          </div>

          <div class="form-group">
            <%= text_field_tag 'video[subject]', @video.subject_list.join(', '), :class => 'form-control', :placeholder => 'Subject' %>
          </div>

          <div class="form-group">
            <%= f.text_area :description, :class => 'form-control', :placeholder => 'Description' %>
          </div>

          <%= link_to('Destroy', '', {
            :remote => true,
            :class => 'btn btn-danger pull-left',
            :data => {
              :toggle => 'modal',
              :target => '#destroyModal'
            }
          }) %>
          <%= f.submit 'Update', :class => 'btn btn-info pull-right' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'videos/edit/destroy_modal', :video => @video %>

app/views/videos/import.html.erb
<% unless @last_import.nil? %>
  <div class="col-md-5 no-padding">
    <div class="panel panel-default module module-import">
      <div class="panel-heading">
        Last Import
      </div>
      <div class="panel-body">
        <p>Your last import on <%= @last_import.time_imported.strftime('%m/%d/%Y at %H:%M') %> was <%= @last_import.success ? '' : 'not ' %> successful.<br>
        <%= @last_import.videos.size %> videos were imported.</p>

        <% unless @last_import.success %>
          <p>Below are listed some errors:</p>
          <ul>
            <% @last_import.messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="<%= @last_import.nil? ? 'col-xs-12' : 'col-md-7' %> no-padding">
  <div class="panel panel-default module module-videos">
    <div class="panel-heading">
    Import videos
    </div>
  <div class="panel-body">
    <p>You can import a list of videos in CSV format. Make sure that the file you use is consistent with the following template:</p>
    <div class="download">
      <%= link_to 'Download Template', download_path(:filename => 'public/video/template.csv'), :class => 'btn btn-default btn-download' %>
    </div>
    <p>Note that you only have to fill in the <code>youtube_id</code> column; the rest are optional.</p>
    <%= form_tag import_videos_path, :multipart => true do %>
    <div class="form-group form-import">
      <%= file_field_tag 'file', :class => 'filestyle', :'data-icon' => false %>
    </div>
  <%= submit_tag 'Import', :class => 'btn btn-primary' %>
<% end %>

app/views/videos/index.html.erb
<div class="video-filter">
  <%= form_tag videos_path, :method => 'get', :class => 'form-search', :id => 'video-search' do %>
    <div class="col-lg-6 col-md-5 no-padding">
      <%= text_field_tag :search, nil, {
        :class => 'form-control', :placeholder => 'Search by video name.', :autofocus => true
      } %>
    </div>

    <div id="status-filter" class="status-check-group col-lg-6 col-md-7 no-padding">
      <div class="btn-group col-xs-12 no-padding" role="group" aria-label="...">
        <% @statuses.each_with_index do |status, i| %>
          <span class="button-checkbox btn-group col-xs-2 no-padding">
            <% check_box = check_box_tag 'statuses[]', status, @default_params[status], :class => 'hidden' %>
            <%= check_box unless i == 0 %>
            <button type="button" class="btn col-xs-12" data-color="<%= status_to_color(status) %>"><%= status.titleize %></button>
            <%= check_box if i == 0 %>
          </span>
        <% end %>

        <select id="subject-filter" name="subjects[]" class="selectpicker show-tick col-xs-4" title="All Subjects" data-selected-text-format="count > 2" multiple>
          <% @subjects.each do |subject| %>
            <option><span><%= subject %></span></option>
          <% end %>
        </select>
      </div>
    </div>
  <% end %>
</div>

<br />

<div id="video-list" class="module-search-results">
</div>

app/views/videos/index.js.erb
$('#video-list').html("<%= escape_javascript(render('videos/index/videos_list', {
  :title => 'Videos',
  :videos => @videos,
  :message_empty => 'Nothing found!',
  :star => true
})) %>");

app/views/videos/new.html.erb
<div class="row centered-form">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default module">
      <div class="panel-heading">
        New Video
      </div>
      <div class="panel-body">
        <%= form_for @video, :html => { :class => 'form-update' } do |f| %>
          <div class="form-group">
            <%= f.text_field :title, :autofocus => true, :class => 'form-control', :placeholder => 'Title' %>
          </div>

          <div class="form-group">
            <%= f.text_field :youtube_id, :class => 'form-control', :placeholder => 'Youtube ID' %>
          </div>

          <div class="form-group">
            <%= text_field_tag 'video[subject]', nil, :class => 'form-control', :placeholder => 'Subject' %>
          </div>

          <div class="form-group">
            <%= f.text_area :description, :class => 'form-control', :placeholder => 'Description' %>
          </div>

          <%= f.submit 'Create', :class => 'btn btn-primary center-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="col-md-8 no-padding">
  <%= render 'videos/show/video_frame', :video => @video %>

  <%= render 'videos/show/actions', :video => @video, :user => current_user, :translation => @user_translation %>

  <%= render 'videos/show/translate_frame', :video => @video, :user => current_user, :translation => @user_translation %>

  <%= render 'videos/translations/translations_frame', :video => @video, :user => current_user, :translations => @completed_translations %>
</div>

<div class="col-md-4 no-padding">
  <%= render 'videos/show/contributors_frame', :translators => @translators, :reviewers => @reviewers %>

  <%= render 'videos/show/similar_videos_frame', :videos => @similar_videos %>
</div>

app/views/videos/toggle_star.js.erb
$('#toggle-star-<%= @video.id %>').html("<%= escape_javascript(
  toggle_star_button(@video)
) %>");

app/views/videos/vote.js.erb
$('#vote-translation-<%= @translation.id %>').html("<%= escape_javascript(
  render 'videos/translations/vote_actions', :video => @video, :translation => @translation
) %>");