config/routes.rb
KhanBurmese::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root :to => 'home#index'
  get 'home' => 'home#dashboard', :as => :dashboard
  get 'manage_dash' => 'home#admin_dashboard', :as => :admin_dashboard

  get 'preview' => 'preview#show', :as => :prototype

  get 'download' => 'files#download'

  resources :users, :only => [ :show, :update, :destroy ] do
    collection do
      get 'leaderboard' => 'users#leaderboard'
    end
    put :change_role
  end

  resources :videos do
    put :toggle_star
    resources :translations do
      post 'submit_amara' => 'translations#submit_amara'
      post 'vote' => 'translations#vote'
      post 'review_mail' => 'translations#review_mail'
    end

    collection do
      get :import
      post :import
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    if user_signed_in?
      flash.keep
      redirect_to dashboard_path
    end
  end

  def admin_dashboard
    authorize! :access, :admin_dashboard

    @statistics = {
      :members => User.count,
      :untranslated_videos => Video.search(nil, [ 'unassigned', 'assigned' ]).length,
      :translated_videos => Video.search(nil, [ 'translated', 'reviewed' ]).size,
      :reviewed_videos => Video.search(nil, [ 'reviewed' ]).size,
    }
  end

  def dashboard
    @assigned_videos = current_user.assigned_videos
    @translated_videos = current_user.translated_videos
    @recently_translated_videos = Video.recently_translated_videos(1.week.ago).take(5)
    @priority_videos = Video.priority_videos.take(5)
    @reviewed_videos = current_user.reviewed_videos
    @after = 1.month.ago
    @leaders = User.leaders(@after).take(3)
  end
end

app/views/home/admin_dashboard.html.erb
<div class="col-sm-4 no-padding">
  <div class="panel panel-default module module-videos">
    <div class="panel-heading">
      <b>Add Videos</b>
    </div>
    <ul class="list-group">
      <li class="list-group-item">
        <b><%= link_to 'Add a Single Video', new_video_path %></b>
      </li>
      <li class="list-group-item">
        <b><%= link_to 'Import a List of Videos', import_videos_path %></b>
      </li>
    </ul>
  </div>
</div>

<div class="col-sm-8 no-padding">
  <div class="panel panel-default module">
    <div class="panel-heading">
      <b>Statistics</b>
    </div>
    <ul class="list-group">
      <li class="list-group-item">
        <span class="badge"><%= @statistics[:members] %></span>
        Members:
      </li>
      <li class="list-group-item">
        <span class="badge"><%= @statistics[:untranslated_videos] %></span>
        Untranslated Videos:
      </li>
      <li class="list-group-item">
        <span class="badge"><%= @statistics[:translated_videos] %></span>
        Translated Videos:
      </li>
      <li class="list-group-item">
        <span class="badge"><%= @statistics[:reviewed_videos] %></span>
        Reviewed Videos:
      </li>
    </div>
  </div>
</div>

app/views/home/dashboard.html.erb
<div class="col-md-8 no-padding">
  <%= render 'videos/index/videos_list', {
    :title => 'Assigned Videos',
    :videos => @assigned_videos,
    :message_empty => 'No videos assigned.',
    :star => true
  } %>

  <%= render 'videos/index/videos_list', {
    :title => 'Top Priority Videos',
    :title_link => videos_path,
    :videos => @priority_videos,
    :message_empty => 'No videos need to be translated quickly.'
  } %>

  <%= render 'videos/index/videos_list', {
    :title => 'Recently Translated Videos',
    :title_link => videos_path(:statuses => [ :translated ]),
    :videos => @recently_translated_videos,
    :message_empty => 'No videos translated recently.'
  } %>
</div>

<div class="col-md-4 no-padding">
  <%= render 'home/dashboard/accomplishments_frame', {
    :assigned => @assigned_videos.length,
    :translated => @translated_videos.length,
    :reviewed => @reviewed_videos.length,
    :user => current_user
  } %>

  <%= render 'home/dashboard/rankings_frame', :leaders => @leaders, :after => @after %>
</div>

app/views/home/index.html.erb
<div class="row">
  <center>
    <div class="module-images">
      <%= image_tag 'instagram-1.jpg', :class => 'large-image' %>
      <%= image_tag 'instagram-2.jpg', :class => 'small-image' %>
      <%= image_tag 'instagram-3.jpg', :class => 'small-image' %>
      <%= image_tag 'instagram-4.jpg', :class => 'small-image' %>
      <%= image_tag 'instagram-9.jpg', :class => 'small-image' %>
      <%= image_tag 'instagram-6.jpg', :class => 'small-image' %>
      <%= image_tag 'instagram-7.jpg', :class => 'small-image' %>
      <div class="spacer"></div>
      <div class="pull-left video-text">
        <h1><b>Contribute to Learning Today!</b></h1>
        <h4>Join us in bringing free education to Myanmar by translating important videos from Khan Academy.</h4>
        <%= link_to 'Get Started', new_user_registration_path, :class => 'btn btn-success' %>
      </div>
      <div class="pull-left video">
        <iframe src="//www.youtube.com/embed/M01-TM92298" frameBorder="0" autoplay="0"></iframe>
      </div>
      <div class="spacer"></div>
      <div class="pull-left text" >
        <h1><b>About Us</b></h1>
        <h4>We are community of volunteers dedicated to provide resources and tools for the translation of Khan Academy videos into the Myanmar language. </h4>
        <h4>For more information, please visit our official website: <a href="http://www.khanacademyburmese.org" target="_blank">khanacademyburmese.org</a></h4>
        <a class="btn btn-primary" href="http://www.khanacademyburmese.org" target="_blank">Learn More</a>
      </div>
      <%= image_tag 'instagram-5.jpg', :class => 'large-image about-image' %>
      <%= image_tag 'instagram-8.jpg', :class => 'small-image about-image' %>
      <%= image_tag 'instagram-10.jpg', :class => 'small-image about-image' %>
      <div class="spacer"></div>
    </div>
  </center>
</div>